include(CheckCCompilerFlag)
function(add_if_flag_compiles flag)
  CHECK_C_COMPILER_FLAG("${flag}" COMPILER_COMPATIBLE_FLAG)
  set(outcome "FAILED")
  if(COMPILER_COMPATIBLE_FLAG)
    foreach(var ${ARGN})
      set(${var} "${flag} ${${var}}" PARENT_SCOPE)
    endforeach()
    set(outcome "COMPILES")
  endif()
  message(STATUS "Checking if ${flag} can be used -- ${outcome}")
endfunction()
